var censusKeys = {"FIPS":"FIPS",
"GEOID":"Geographic Identifier",
"NAME":"Area Name",
"QName":"Qualifying Name",
"STUSAB":"State Postal Abbreviation",
"SUMLEV":"Summary Level",
"GEOCOMP":" Geographic Component",
"FILEID":"File identification",
"LOGRECNO":"Logical Record Number",
"US":"  US",
"REGION":"Census Region",
"DIVISION":"Census Division",
"STATECE":" State (Census Code)",
"STATE":"State (FIPS Code)",
"COUNTY":"County of current residence",
"COUSUB":"County Subdivision (FIPS)",
"PLACE":"Place (FIPS Code)",
"PLACESE":" Place (State FIPS + Place FIPS)",
"TRACT":"Census Tract",
"BLKGRP":"Block Group",
"CONCIT":"Consolidated City",
"AIANHH":"American Indian Area/Alaska Native Area/Hawaiian Home Land (Census)",
"AIANHHFP":"American Indian Area/Alaska Native Area/Hawaiian Home Land (FIPS)",
"AIHHTLI":" American Indian Trust Land/Hawaiian Home Land Indicator",
"AITSCE":"American Indian Tribal Subdivision (Census)",
"AITS":"American Indian Tribal Subdivision (FIPS)",
"ANRC":"Alaska Native Regional Corporation (FIPS)",
"CBSA":"Metropolitan and Micropolitan Statistical Area",
"CSA":" Combined Statistical Area",
"METDIV":"Metropolitan Division",
"MACC":"Metropolitan Area Central City",
"MEMI":"Metropolitan/Micropolitan Indicator Flag",
"NECTA":"New England City and Town Area",
"CNECTA":"New England City and Town Area",
"NECTADIV":"New England City and Town Area Division",
"UA":"  Urban Area",
"UACP":"Urban Area Central Place",
"CDCURR":"Current Congressional District ***",
"SLDU":"State Legislative District Upper",
"SLDL":"State Legislative District Lower",
"VTD":" Voting District",
"ZCTA3":"ZIP Code Tabulation Area (3-digit)",
"ZCTA5":"5-digit ZIP Code Tabulation Area",
"SUBMCD":"Subminor Civil Division (FIPS)",
"SDELM":"State-School District (Elementary)",
"SDSEC":"State-School District (Secondary)",
"SDUNI":"State-School District (Unified)",
"UR":"  Urban/Rural",
"PCI":" Principal City Indicator",
"TAZ":" Traffic Analysis Zone",
"UGA":" Urban Growth Area",
"BTTR":"Tribal Tract",
"BTBG":"Tribal Block Group",
"PUMA5":"Public Use Microdata Area - 5% File",
"PUMA1":"Public Use Microdata Area - 1% File",
"A00001_001":"Total Population",
"A00002_001":"Total Population",
"A00002_002":"Population Density (Per Sq. Mile)",
"A00002_003":"Area (Land)",
"A00003_001":"Area Total:",
"A00003_002":"Area Total: Area (Land)",
"A00003_003":"Area Total: Area (Water)",
"A02001_001":"Total Population:",
"A02001_002":"Total Population: Male",
"A02001_003":"Total Population: Female",
"A01001_001":"Total Population:",
"A01001_002":"Total Population: Under 5 Years",
"A01001_003":"Total Population: 5 to 9 Years",
"A01001_004":"Total Population: 10 to 14 Years",
"A01001_005":"Total Population: 15 to 17 Years",
"A01001_006":"Total Population: 18 to 24 Years",
"A01001_007":"Total Population: 25 to 34 Years",
"A01001_008":"Total Population: 35 to 44 Years",
"A01001_009":"Total Population: 45 to 54 Years",
"A01001_010":"Total Population: 55 to 64 Years",
"A01001_011":"Total Population: 65 to 74 Years",
"A01001_012":"Total Population: 75 to 84 Years",
"A01001_013":"Total Population: 85 Years and Over",
"A10008_001":"Households:",
"A10008_002":"Households: Family Households",
"A10008_003":"Households: Family Households: Married-Couple Family",
"A10008_004":"Households: Family Households: Other Family",
"A10008_005":"Households: Family Households: Other Family: Male Householder, No Wife Present",
"A10008_006":"Households: Family Households: Other Family: Female Householder, No Husband Present",
"A10008_007":"Households: Nonfamily Households",
"A10008_008":"Households: Nonfamily Households: Male Householder",
"A10008_009":"Households: Nonfamily Households: Female Householder",
"A10024_001":"Occupied Housing Units",
"A10024_002":"Occupied Housing Units: 1-Person Household",
"A10024_003":"Occupied Housing Units: 2-Person Household",
"A10024_004":"Occupied Housing Units: 3-Person Household",
"A10024_005":"Occupied Housing Units: 4-Person Household",
"A10024_006":"Occupied Housing Units: 5-Person Household",
"A10024_007":"Occupied Housing Units: 6-Person Household",
"A10024_008":"Occupied Housing Units: 7-or-More Person Household",
"A10003_001":"Average Household Size",
"A11001_001":"Population 15 Years and Over:",
"A11001_002":"Population 15 Years and Over: Never Married",
"A11001_003":"Population 15 Years and Over: Now Married (Not Including Separated)",
"A11001_004":"Population 15 Years and Over: Separated",
"A11001_005":"Population 15 Years and Over: Widowed",
"A11001_006":"Population 15 Years and Over: Divorced",
"A14006_001":"Median Household Income (In 2019 Inflation Adjusted Dollars)",
"A14024_001":"Per Capita Income (In 2019 Inflation Adjusted Dollars)"}